/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Destroy the session.
         *
         *     Succeeds even when nothing matched. Reporting whether a session existed
         *     would answer a question the caller has no business asking, and there is
         *     nothing useful for a client to do differently either way.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Endpoint */
        get: operations["list_endpoint_v1_buckets_get"];
        put?: never;
        /** Create Endpoint */
        post: operations["create_endpoint_v1_buckets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets/{bucket}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Endpoint */
        get: operations["list_endpoint_v1_buckets__bucket__secrets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets/{bucket}/secrets/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Endpoint */
        get: operations["get_endpoint_v1_buckets__bucket__secrets__key__get"];
        /** Put Endpoint */
        put: operations["put_endpoint_v1_buckets__bucket__secrets__key__put"];
        post?: never;
        /** Delete Endpoint */
        delete: operations["delete_endpoint_v1_buckets__bucket__secrets__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Endpoint */
        delete: operations["delete_endpoint_v1_buckets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Prove the process is up and the database is reachable.
         *
         *     Uses SELECT 1 rather than querying a table, because SP1 deliberately
         *     creates no tables.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Endpoint */
        get: operations["list_endpoint_v1_keys_get"];
        put?: never;
        /** Create Endpoint */
        post: operations["create_endpoint_v1_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Endpoint */
        delete: operations["revoke_endpoint_v1_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiKeyData
         * @description Metadata only. Never the token, never the stored hash.
         */
        ApiKeyData: {
            /** Buckets */
            buckets: string[];
            /** Can Reveal */
            can_reveal: boolean;
            /** Can Write */
            can_write: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Lookup Id */
            lookup_id: string;
            /** Name */
            name: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * BucketData
         * @description What a bucket looks like from outside.
         *
         *     Carries no wrapped_dek and no kek_version. The key tier is not a user
         *     facing concept and nothing about it leaves the server.
         */
        BucketData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Secret Count */
            secret_count: number;
        };
        /** CreateBucketRequest */
        CreateBucketRequest: {
            /** Name */
            name: string;
        };
        /** CreateKeyRequest */
        CreateKeyRequest: {
            /** Buckets */
            buckets: string[];
            /**
             * Can Reveal
             * @default false
             */
            can_reveal: boolean;
            /**
             * Can Write
             * @default false
             */
            can_write: boolean;
            /** Expires At */
            expires_at?: string | null;
            /** Name */
            name: string;
        };
        /**
         * CreatedApiKeyData
         * @description The one response in this API that carries a live credential.
         */
        CreatedApiKeyData: {
            /** Buckets */
            buckets: string[];
            /** Can Reveal */
            can_reveal: boolean;
            /** Can Write */
            can_write: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Lookup Id */
            lookup_id: string;
            /** Name */
            name: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Token */
            token: string;
        };
        /** DeletedData */
        DeletedData: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * Err
         * @description Failure arm of the ADR 002 response envelope.
         */
        Err: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HealthData */
        HealthData: {
            /** Db */
            db: string;
        };
        /** LogoutData */
        LogoutData: {
            /** Signed Out */
            signed_out: boolean;
        };
        /** MeData */
        MeData: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** Ok[BucketData] */
        Ok_BucketData_: {
            data: components["schemas"]["BucketData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[CreatedApiKeyData] */
        Ok_CreatedApiKeyData_: {
            data: components["schemas"]["CreatedApiKeyData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[DeletedData] */
        Ok_DeletedData_: {
            data: components["schemas"]["DeletedData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[HealthData] */
        Ok_HealthData_: {
            data: components["schemas"]["HealthData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[LogoutData] */
        Ok_LogoutData_: {
            data: components["schemas"]["LogoutData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[MeData] */
        Ok_MeData_: {
            data: components["schemas"]["MeData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[RevokedData] */
        Ok_RevokedData_: {
            data: components["schemas"]["RevokedData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[SecretData] */
        Ok_SecretData_: {
            data: components["schemas"]["SecretData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[SecretValueData] */
        Ok_SecretValueData_: {
            data: components["schemas"]["SecretValueData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[dict[str, str]] */
        Ok_dict_str__str__: {
            /** Data */
            data: {
                [key: string]: string;
            };
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[list[ApiKeyData]] */
        Ok_list_ApiKeyData__: {
            /** Data */
            data: components["schemas"]["ApiKeyData"][];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[list[BucketData]] */
        Ok_list_BucketData__: {
            /** Data */
            data: components["schemas"]["BucketData"][];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[list[SecretData]] */
        Ok_list_SecretData__: {
            /** Data */
            data: components["schemas"]["SecretData"][];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** PutSecretRequest */
        PutSecretRequest: {
            /** Value */
            value: string;
        };
        /** RevokedData */
        RevokedData: {
            /** Revoked */
            revoked: boolean;
        };
        /**
         * SecretData
         * @description Metadata only.
         *
         *     No value and no length: a length narrows the search space for a password
         *     or a token, and invariant 7 says metadata only.
         */
        SecretData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key Name */
            key_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SecretValueData */
        SecretValueData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key Name */
            key_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_LogoutData_"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_MeData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    list_endpoint_v1_buckets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_list_BucketData__"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    create_endpoint_v1_buckets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBucketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_BucketData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    list_endpoint_v1_buckets__bucket__secrets_get: {
        parameters: {
            query?: {
                reveal?: boolean;
            };
            header?: never;
            path: {
                bucket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_list_SecretData__"] | components["schemas"]["Ok_dict_str__str__"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    get_endpoint_v1_buckets__bucket__secrets__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                bucket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_SecretValueData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    put_endpoint_v1_buckets__bucket__secrets__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                bucket: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSecretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_SecretData_"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_SecretData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    delete_endpoint_v1_buckets__bucket__secrets__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                bucket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_SecretData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    delete_endpoint_v1_buckets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_DeletedData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_HealthData_"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    list_endpoint_v1_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_list_ApiKeyData__"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    create_endpoint_v1_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_CreatedApiKeyData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    revoke_endpoint_v1_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_RevokedData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
}
