/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Destroy the session.
         *
         *     Succeeds even when nothing matched. Reporting whether a session existed
         *     would answer a question the caller has no business asking, and there is
         *     nothing useful for a client to do differently either way.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Prove the process is up and the database is reachable.
         *
         *     Uses SELECT 1 rather than querying a table, because SP1 deliberately
         *     creates no tables.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Err
         * @description Failure arm of the ADR 002 response envelope.
         */
        Err: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HealthData */
        HealthData: {
            /** Db */
            db: string;
        };
        /** LogoutData */
        LogoutData: {
            /** Signed Out */
            signed_out: boolean;
        };
        /** MeData */
        MeData: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** Ok[HealthData] */
        Ok_HealthData_: {
            data: components["schemas"]["HealthData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[LogoutData] */
        Ok_LogoutData_: {
            data: components["schemas"]["LogoutData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[MeData] */
        Ok_MeData_: {
            data: components["schemas"]["MeData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_LogoutData_"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_MeData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_HealthData_"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
}
