/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Destroy the session.
         *
         *     Succeeds even when nothing matched. Reporting whether a session existed
         *     would answer a question the caller has no business asking, and there is
         *     nothing useful for a client to do differently either way.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Endpoint */
        get: operations["list_endpoint_v1_buckets_get"];
        put?: never;
        /** Create Endpoint */
        post: operations["create_endpoint_v1_buckets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Endpoint */
        delete: operations["delete_endpoint_v1_buckets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Prove the process is up and the database is reachable.
         *
         *     Uses SELECT 1 rather than querying a table, because SP1 deliberately
         *     creates no tables.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BucketData
         * @description What a bucket looks like from outside.
         *
         *     Carries no wrapped_dek and no kek_version. The key tier is not a user
         *     facing concept and nothing about it leaves the server.
         */
        BucketData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** CreateBucketRequest */
        CreateBucketRequest: {
            /** Name */
            name: string;
        };
        /** DeletedData */
        DeletedData: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * Err
         * @description Failure arm of the ADR 002 response envelope.
         */
        Err: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Db */
            db: string;
        };
        /** LogoutData */
        LogoutData: {
            /** Signed Out */
            signed_out: boolean;
        };
        /** MeData */
        MeData: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** Ok[BucketData] */
        Ok_BucketData_: {
            data: components["schemas"]["BucketData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[DeletedData] */
        Ok_DeletedData_: {
            data: components["schemas"]["DeletedData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[HealthData] */
        Ok_HealthData_: {
            data: components["schemas"]["HealthData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[LogoutData] */
        Ok_LogoutData_: {
            data: components["schemas"]["LogoutData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[MeData] */
        Ok_MeData_: {
            data: components["schemas"]["MeData"];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** Ok[list[BucketData]] */
        Ok_list_BucketData__: {
            /** Data */
            data: components["schemas"]["BucketData"][];
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_LogoutData_"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_MeData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    list_endpoint_v1_buckets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_list_BucketData__"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    create_endpoint_v1_buckets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBucketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_BucketData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
    delete_endpoint_v1_buckets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_DeletedData_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok_HealthData_"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Err"];
                };
            };
        };
    };
}
